services:
  - type: web
    name: spitalert-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT --workers 4 --timeout 120
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: spitalert-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: SCRAPING_INTERVAL
        value: 900
      - key: DEBUG
        value: false
    autoDeploy: true

databases:
  - name: spitalert-db
    databaseName: spitalert
    plan: free 