services:
  # API Service
  - type: web
    name: spitalert-api
    env: docker
    region: frankfurt  # EU region
    plan: starter
    healthCheckPath: /
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: '["https://api.spitalert.com"]'
      - key: POSTGRES_USER
        sync: false  # Chiedi a Render di gestire questo valore
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_SERVER
        fromService:
          type: postgres
          name: spitalert-db
          property: host
      - key: POSTGRES_DB
        value: spitalert
      - key: REDIS_URL
        value: "redis://red-curpt2rqf0us73cvr4i0:6379"
    
  # # Database Service
  # - type: postgres
  #   name: spitalert-db
  #   region: frankfurt
  #   plan: starter
  #   ipAllowList: []  # Accesso solo dai servizi Render 